# Generated by Django 4.0.3 on 2022-05-07 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_routes', '0002_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_suspend_user', 'Can suspend user')], 'verbose_name_plural': 'Users'},
        ),
    ]
