# Generated by Django 4.0.3 on 2022-07-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_routes', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
