# Generated by Django 4.0.3 on 2022-10-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_routes', '0005_alter_user_firstname_alter_user_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
