# Generated by Django 4.0.3 on 2022-03-13 15:05

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('rest_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_code',
            field=hashid_field.field.HashidField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', blank=True, min_length=6, null=True, prefix='', unique=True),
        ),
    ]
