# Generated by Django 4.0.3 on 2022-03-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_auth', '0002_user_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
